# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/giuseppefrancione/optimfrogcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/giuseppefrancione/optimfrogcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/giuseppefrancione/optimfrogcpp/CMakeFiles /Users/giuseppefrancione/optimfrogcpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/giuseppefrancione/optimfrogcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named optimfrogcpp_lib

# Build rule for target.
optimfrogcpp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 optimfrogcpp_lib
.PHONY : optimfrogcpp_lib

# fast build rule for target.
optimfrogcpp_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/build
.PHONY : optimfrogcpp_lib/fast

#=============================================================================
# Target rules for targets named optimfrogcpp

# Build rule for target.
optimfrogcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 optimfrogcpp
.PHONY : optimfrogcpp

# fast build rule for target.
optimfrogcpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp.dir/build.make CMakeFiles/optimfrogcpp.dir/build
.PHONY : optimfrogcpp/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp.dir/build.make CMakeFiles/optimfrogcpp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp.dir/build.make CMakeFiles/optimfrogcpp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp.dir/build.make CMakeFiles/optimfrogcpp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/optimfrog.o: src/optimfrog.cpp.o
.PHONY : src/optimfrog.o

# target to build an object file
src/optimfrog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog.cpp.o
.PHONY : src/optimfrog.cpp.o

src/optimfrog.i: src/optimfrog.cpp.i
.PHONY : src/optimfrog.i

# target to preprocess a source file
src/optimfrog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog.cpp.i
.PHONY : src/optimfrog.cpp.i

src/optimfrog.s: src/optimfrog.cpp.s
.PHONY : src/optimfrog.s

# target to generate assembly for a file
src/optimfrog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog.cpp.s
.PHONY : src/optimfrog.cpp.s

src/optimfrog_decoder.o: src/optimfrog_decoder.cpp.o
.PHONY : src/optimfrog_decoder.o

# target to build an object file
src/optimfrog_decoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder.cpp.o
.PHONY : src/optimfrog_decoder.cpp.o

src/optimfrog_decoder.i: src/optimfrog_decoder.cpp.i
.PHONY : src/optimfrog_decoder.i

# target to preprocess a source file
src/optimfrog_decoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder.cpp.i
.PHONY : src/optimfrog_decoder.cpp.i

src/optimfrog_decoder.s: src/optimfrog_decoder.cpp.s
.PHONY : src/optimfrog_decoder.s

# target to generate assembly for a file
src/optimfrog_decoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder.cpp.s
.PHONY : src/optimfrog_decoder.cpp.s

src/optimfrog_decoder_entropy.o: src/optimfrog_decoder_entropy.cpp.o
.PHONY : src/optimfrog_decoder_entropy.o

# target to build an object file
src/optimfrog_decoder_entropy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder_entropy.cpp.o
.PHONY : src/optimfrog_decoder_entropy.cpp.o

src/optimfrog_decoder_entropy.i: src/optimfrog_decoder_entropy.cpp.i
.PHONY : src/optimfrog_decoder_entropy.i

# target to preprocess a source file
src/optimfrog_decoder_entropy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder_entropy.cpp.i
.PHONY : src/optimfrog_decoder_entropy.cpp.i

src/optimfrog_decoder_entropy.s: src/optimfrog_decoder_entropy.cpp.s
.PHONY : src/optimfrog_decoder_entropy.s

# target to generate assembly for a file
src/optimfrog_decoder_entropy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder_entropy.cpp.s
.PHONY : src/optimfrog_decoder_entropy.cpp.s

src/optimfrog_decoder_predictor.o: src/optimfrog_decoder_predictor.cpp.o
.PHONY : src/optimfrog_decoder_predictor.o

# target to build an object file
src/optimfrog_decoder_predictor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder_predictor.cpp.o
.PHONY : src/optimfrog_decoder_predictor.cpp.o

src/optimfrog_decoder_predictor.i: src/optimfrog_decoder_predictor.cpp.i
.PHONY : src/optimfrog_decoder_predictor.i

# target to preprocess a source file
src/optimfrog_decoder_predictor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder_predictor.cpp.i
.PHONY : src/optimfrog_decoder_predictor.cpp.i

src/optimfrog_decoder_predictor.s: src/optimfrog_decoder_predictor.cpp.s
.PHONY : src/optimfrog_decoder_predictor.s

# target to generate assembly for a file
src/optimfrog_decoder_predictor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/optimfrogcpp_lib.dir/build.make CMakeFiles/optimfrogcpp_lib.dir/src/optimfrog_decoder_predictor.cpp.s
.PHONY : src/optimfrog_decoder_predictor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... optimfrogcpp"
	@echo "... optimfrogcpp_lib"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/optimfrog.o"
	@echo "... src/optimfrog.i"
	@echo "... src/optimfrog.s"
	@echo "... src/optimfrog_decoder.o"
	@echo "... src/optimfrog_decoder.i"
	@echo "... src/optimfrog_decoder.s"
	@echo "... src/optimfrog_decoder_entropy.o"
	@echo "... src/optimfrog_decoder_entropy.i"
	@echo "... src/optimfrog_decoder_entropy.s"
	@echo "... src/optimfrog_decoder_predictor.o"
	@echo "... src/optimfrog_decoder_predictor.i"
	@echo "... src/optimfrog_decoder_predictor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

